dbt_github:
  outputs:
    dev:
      dataset: dev
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "/Users/oleg/de-zoomcamp-project-v2/.google/terraform-service-account.json"
      location: europe-west6
      method: service-account
      priority: interactive
      project: de-zoomcamp-2023-project-v2
      threads: 1
      type: bigquery
  target: dev

dbt_github_better:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      priority: interactive
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_PATH') }}"
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: dev
      location: "{{ env_var('GCP_REGION') }}"
      threads: 1
      job_retries: 1
      job_execution_timeout_seconds: 300
